apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-woodpecker-server-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/woodpecker
  persistentVolumeReclaimPolicy: Retain
