---
- name: Ensure curl is installed
  apt:
    name: curl
    state: present
  become: true
  when: inventory_hostname == groups[server_group][0] or ansible_host == groups[server_group][0]

- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: inventory_hostname == groups[server_group][0] or ansible_host == groups[server_group][0]

- name: Install Helm
  command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  when: inventory_hostname == groups[server_group][0] or ansible_host == groups[server_group][0]
