- name: Mostrar chaves do secret "{{ nome_secret }}"
  ansible.builtin.shell: |
    kubectl get secret {{ nome_secret }} -n global-secrets -o json | jq -r '.data | to_entries[] | "\(.key)=\(.value)"'
  register: secret_data
  changed_when: false

- name: Decodificar base64 do secret "{{ nome_secret }}"
  ansible.builtin.set_fact:
    decoded_secret_{{ nome_secret | replace('.', '_') }}: "{{ dict(secret_data.stdout_lines | map('split', '=') | map('first') | list | zip(secret_data.stdout_lines | map('split', '=') | map('last') | map('b64decode') | list)) }}"

- name: Exibir secret "{{ nome_secret }}"
  ansible.builtin.debug:
    msg: "{{ lookup('vars', 'decoded_secret_' + nome_secret | replace('.', '_')) }}"
