- hosts: server
  tasks:
    - name: Garantir que esses namespaces existam
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
        state: present
      loop:
        - argocd
        - cert-manager
        - cloudflared
        - external-dns
        - global-secrets
        - k8up-operator
        - monitoring-system
        - metallb-system
      when: inventory_hostname == groups['server'][0]