- hosts: server
  tasks:
    - name: Apagar os namespaces do cluster
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
        state: absent
      loop:
        - argocd
        - cert-manager
        - cloudflared
        - external-dns
        - global-secrets
        - k8up-operator
        - monitoring-system
        - metallb-system
        - gitea
        - kanidm
        - matrix
        - paperless
        - rook-ceph
        - speedtest
        - tailscale
        - volsync-system
        - wireguard
        - woodpecker
        - zot
      when: inventory_hostname == groups['server'][0]
