- hosts: server
  gather_facts: false
  vars:
    secrets:
      - dex.gitea
      - dex.grafana
      - external
      - gitea.admin
      - gitea.renovate
      - gitea.woodpecker
      - paperless.admin
      - registry.admin
      - woodpecker.agent

  tasks:

    - name: Incluir task para listar secrets do namespace global-secrets
      when: inventory_hostname == groups['server'][0]
      ansible.builtin.include_tasks: listar_secrets.yaml
      loop: "{{ secrets }}"
      loop_control:
        loop_var: nome_secret

    - name: Gravar saída das senhas em arquivo local
      when: inventory_hostname == groups['server'][0]
      copy:
        content: |
          ArgoCD: {{ argocd_password.stdout | default('') }}
          Kanidm: {{ kanidm_secret.stdout | default('') }}
          Gitea: {{ gitea_secret.stdout | default('') }}
          Grafana: {{ grafana_secret.stdout | default('') }}
          Kanidm Admin: {{ admin_recovery.stdout_lines | default([]) }}
          kanidm Idm Admin: {{ idm_admin_recovery.stdout_lines | default([]) }}
        dest: /tmp/senhas_output.log
