- name: Post Install
  hosts: server
  gather_facts: false
  tasks:
    - block:

        - name: Sincronizar projeto do host local para o nó master
          ansible.posix.synchronize:
            src: "../../"
            dest: "{{ path_project_master_node }}"
            recursive: yes
            delete: no
            rsync_opts:
              - "--exclude=.git"
              - "--exclude=.idea/"
              - "--exclude=.DS_Store"
              - "--exclude=__pycache__"
              - "--exclude=k3s-ansible/"
              - "--exclude=ProxmoxVE/"
          delegate_to: localhost
          run_once: true

        - name: Executar make post-install na pasta "{{ path_project_master_node }}"
          shell: |
            cd /tmp/multiversonline
            make post-install

      when: inventory_hostname == groups[server_group][0]
