    - name: Add cilium helm repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: "{{ cilium_repo_url }}"
      when: inventory_hostname == groups[server_group][0]
      ignore_errors: true

    - name: Install cilium chart
      command:
        cmd: "helm upgrade --install cilium cilium/cilium /
              --version {{cilium_version}} /
              -n {{ cilium_namespace }} {{ cilium_values }} /
              --kubeconfig ~{{ ansible_user }}/.kube/config"
      when: inventory_hostname == groups[server_group][0]


