---
cilium_iface: "ens18"
cilium_version: 1.17.3
cilium_namespace: "kube-system"
cilium_repo_url: "https://helm.cilium.io/"
cilium_values: " --set operator.replicas=1 \
                 --set kubeProxyReplacement=true \
                 --set k8sServiceHost=127.0.0.1 \
                 --set k8sServicePort=6443 \
                 --set hubble.relay.enabled=true  \
                 --set hubble.ui.enabled=true "

