---
cilium_iface: "ens18"
cilium_version: 1.17.3
cilium_namespace: "kube-system"
cilium_repo_url: "https://helm.cilium.io/"
cilium_values: " --set operator.replicas=1 --set hubble.relay.enabled=true --set hubble.ui.enabled=true "

