app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: portainer/portainer-ce
            tag: latest
          args:
            - "--http-enabled"
            - "--http-port=9000"
            - "--admin-password-file=/data/.admin_pass"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
  service:
    main:
      ports:
        http:
          port: 9000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host portainer.multiversonline.com.br
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: portainer-tls-certificate
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClass: rook-ceph-block
      advancedMounts:
        main:
          main:
            - path: /data
