app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/ollama/ollama
            tag: latest
    ui:
      containers:
        main:
          image:
            repository: ghcr.io/open-webui/open-webui
            tag: latest
          env:
            OLLAMA_BASE_URL: http://ollama:11434
  service:
    main:
      ports:
        http:
          port: 11434
          protocol: HTTP
      models:
        - llava
        - gemma3
    ui:
      controller: ui
      ports:
        http:
          port: 8080
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &ollamaHost ollama.multiversonline.com.br
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
        - host: &uiHost ai.multiversonline.com.br
          paths:
            - path: /
              pathType: Prefix
              service:
                name: ui
                port: http
      tls:
        - hosts:
            - *ollamaHost
            - *uiHost
          secretName: ollama-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 30Gi
      advancedMounts:
        main:
          main:
            - path: /root/.ollama
    ui:
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        ui:
          main:
            - path: /app/backend/data