- name: Executar make post-install na pasta /tmp/multiversonline/
  shell: |
    cd /tmp/multiversonline/
    make post-install
  when: inventory_hostname == groups[server_group][0] or ansible_host == groups[server_group][0]


