argo-cd:
  server:
    metrics: &metrics
      enabled: false
      serviceMonitor:
        enabled: false
  controller:
    metrics: *metrics
  repoServer:
    metrics: *metrics
  redis:
    metrics: *metrics
  applicationSet:
    enabled: true

argocd-apps:
  applicationsets:
    root:
      generators:
        - git:
            repoURL: &repoURL https://github.com/candradebh/multiversonline
            revision: &revision dozero
            directories:
              - path: system/*
              - path: platform/*
      template:
        spec:
          source:
            repoURL: *repoURL
            targetRevision: *revision
